The Numpy Stack in Python
===========

Compare a List to a NumPy array:
--

import numpy as np

L = [1,2,3]
A = np.array([1,2,3])

for e in L:
    print e
    
for e in A:
    print e

In [3]:
L.append(4)
L

[1, 2, 3, 4, 4]

or 

In [5]:
L = L + [5]
L

[1, 2, 3, 4, 4, 5]

In [6]:
L2 = []
for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 8, 10]

There is no method of append on a NumPy array:
We can use vector addition
----

In [7]:
A + A

array([2, 4, 6])

So the 1st lesson is + sign with Lists does concatenation while + sign with NumPy does vector addition.
---

In [9]:
2*L

[1, 2, 3, 4, 4, 5, 1, 2, 3, 4, 4, 5]

In [10]:
2*A

array([2, 4, 6])

If you wanted to get the List elements to multiply, then you need to use the for loop.
---

In [11]:
L2 = []
for e in L:
    L2.append(e*e)
L2

[1, 4, 9, 16, 16, 25]

In [12]:
A**2

array([1, 4, 9])

In [13]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [14]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [15]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

Dot Products
=====

In [17]:
a = np.array([1,2])
b = np.array([2,1])

Slow dot product using for loops:
---

In [18]:
dot = 0
for e,f in zip(a,b):
    dot += e*f

dot

4

Fast using NumPy:
---

In [19]:
np.sum(a*b)

4

or as an alternative you could use the sum function as it's a instance method of numpy array itself

In [20]:
(a*b).sum()

4

In [21]:
np.dot(a,b)

4

In [22]:
a.dot(b)

4

In [23]:
b.dot(a)

4