The Numpy Stack in Python
===========

Compare a List to a NumPy array:
--

In [1]:
import numpy as np

L = [1,2,3]
A = np.array([1,2,3])

for e in L:
    print e
    
for e in A:
    print e

1
2
3
1
2
3


In [2]:
L.append(4)
L

[1, 2, 3, 4]

or 

In [3]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [4]:
L2 = []
for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 10]

There is no method of append on a NumPy array:
We can use vector addition
----

In [5]:
A + A

array([2, 4, 6])

So the 1st lesson is + sign with Lists does concatenation while + sign with NumPy does vector addition.
---

In [6]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
2*A

array([2, 4, 6])

If you wanted to get the List elements to multiply, then you need to use the for loop.
---

In [8]:
L2 = []
for e in L:
    L2.append(e*e)
L2

[1, 4, 9, 16, 25]

In [9]:
A**2

array([1, 4, 9])

In [10]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [11]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [12]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

Dot Products
=====
$\mathbf{a}\cdot \mathbf{b}=\mathbf{a}^T\mathbf{b}=\sum _{d=1}^D a_d b_d$

$\mathbf{a} \cdot \mathbf{b}=\| \mathbf{a} \|\| \mathbf{b} \|\cos \theta _{\text{ab}}$

$\cos \theta _{\text{ab}}=\frac{\mathbf{a}^T\mathbf{b}}{\| \mathbf{a} \|\| \mathbf{b} \|}$

In [13]:
a = np.array([1,2])
b = np.array([2,1])

Slow dot product using for loops:
---

In [14]:
dot = 0
for e,f in zip(a,b):
    dot += e*f

dot

4

Fast using NumPy:
---

In [15]:
np.sum(a*b)

4

or as an alternative you could use the sum function as it's a instance method of numpy array itself

In [16]:
(a*b).sum()

4

With NumPy there's a more convenient way through the dot() function.
---

In [17]:
np.dot(a,b)

4

In [18]:
a.dot(b)

4

In [19]:
b.dot(a)

4

Angle between vectors requires us to calculate the length or magnitude of the vectors.
---
$\| \mathbf{a} \|=\sqrt{a_1^2+a_2^2+a_3^2+...+a_n^2+}$

In [20]:
amag=np.sqrt((a*a).sum())
amag

2.2360679774997898

As part of the Linear Algebra library within NumPy, we can use a convenient function: np.linalg.norm()

In [21]:
amag=np.linalg.norm(a)
amag

2.2360679774997898

Let's calculate the angle:

In [22]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.79999999999999982

In [23]:
angle=np.arccos(cosangle)
angle

0.6435011087932847

Let's compare the for loop version of the dot product to numpy internal function with respect to speed.
---

In [24]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e*f
    return result

t0 = datetime.now()
for t in xrange(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in xrange(T):
    a.dot(b)
dt2 = datetime.now() - t0

print "dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds()
print "For Loop, dt1 (seconds):", dt1.total_seconds()
print "Numpy, dt2 (seconds):", dt2.total_seconds()

dt1 / dt2: 36.8414512526
For Loop, dt1 (seconds): 9.235415
Numpy, dt2 (seconds): 0.25068


Vectors & Matrices
===
We've seen that a NumPy array's is like a vector.  We can add, multiply, and do elementwise operations like square them.  Matrices are similiar to lists of lists; in fact, you can use a list of lists.

In [25]:
M = np.array([[1,2],[3,4]])

So the convention is that the 1st index is the row and the 2nd is the column.  Let's create and actual lists of list for reference.

In [26]:
L = [[1,2],[3,4]]

Say we want to get an element of the matrix to get the 1.  With a List we would 1st index the row and that would give us the 1st list which contains [1,2].

In [27]:
L[0]

[1, 2]

In [28]:
L[0][0]

1

Notice we can do the same thing to the numpy array.

In [29]:
M[0][0]

1

Here's a shorthand notation like matlab with a comma.

In [30]:
M[0,0]

1

There is an actual datatype in NumPy called a matrix.

In [31]:
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

Note: This works somewhat similarly to a numpy array, but it's not exactly the same.  Most of the time, we use NumPy arrays and the official documentation recommends against using matrix.  So if you see or plan to use matrix, then you should try to convert it to an array. You can do that by using np.array(M2).

In [32]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

Even though this is an array, we still have convenient matrix operations.  So as an example A.T gives use the transpose.

In [33]:
A.T

array([[1, 3],
       [2, 4]])

Generating Matrices to Work With
===

Sometimes you just need some arrays to try stuff out.  What if I want an array of size 100 or with random numbers. Here's an array of all zeros.

In [34]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

A 10x10 matrix of all zeros.

In [35]:
Z = np.zeros((10,10))
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Equivalently, a matrix of all 1s.

In [36]:
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

Let's create a uniformly distributed random matrix.

R = np.random.random((10,10))
R

For a Gaussian distributed random 10x10 matrix with a Mean of 0 and Standard Deviation of 1.

In [37]:
G = np.random.randn(10,10)
G

array([[-0.78528933,  0.02333598,  0.72289526, -1.81322995, -2.05725693,
         0.2680813 ,  0.51308505,  0.18405994, -0.07614378, -0.79726766],
       [ 0.20593572,  1.46022517, -0.04705986, -1.22271517,  0.39509515,
         0.83017319, -0.1720944 , -0.87784952, -0.62385341,  0.04497147],
       [ 0.58742697,  0.84390151, -1.56750578, -1.28345262, -2.1939128 ,
         1.39242005,  0.13994086,  0.43047877,  1.58934731,  0.21768195],
       [-2.10804892,  0.61774865,  1.08445804, -0.97467414, -1.39609876,
         0.12067709,  0.7265621 ,  0.03723662,  0.49430292,  0.56770374],
       [ 0.1758453 , -0.65009788,  0.25947429, -0.02558386, -0.94264456,
         1.07447349,  0.61511711, -0.82422886,  0.94681037, -0.12241748],
       [ 0.49256403, -0.84379529,  0.28270737, -0.24891206,  0.63927156,
         1.22164393,  0.25803829, -2.35212996, -0.3028698 , -1.4823608 ],
       [ 1.03177462, -2.04681334, -0.91106412, -0.37632641,  0.89254904,
         0.333834  , -0.0842759 , -0.38658778

NumPy array also have convenient functions to calculate descriptive statistics.

In [38]:
G.mean()

-0.077637180380637535

In [39]:
G.var()

1.0150904342849296

Matrix Products
===
Remember from Linear Algebra in order for multiplication between 2 matrices to happen, the inner dimensions must match.

(1) If we have A of size (2,3) and B of size (3,3)

    (a) We can multiply AB (inner dimensions is 3)
    
    (b) We cannot multiply BA (inner dimensions is 3/2)

(2) $C(i,j) = \sum_k^KA(i,k)B(k,j)$

(3) (i,j)th entry of C is the dot product of row A(i,:) and column B(:,j)

(4) In NumPy: C = A.dot(B)

It's very natural to want to do C(i,j)=A(i,j)*B(i,j) which is element-wise multiplication.  The asterisk does this for vectors and it also works for multidimensional arrays.

(5) In Deep Learning the operators $\otimes$ or $\circledcirc$ sometimes denote element-wise multiplication.

In [40]:
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [41]:
Ainv.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [42]:
A.dot(Ainv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [43]:
np.linalg.det(A)

-2.0000000000000004

In [44]:
np.diag(A)

array([1, 4])

In [45]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

Outer Product & Inner Product
---
Outer Product is the Tensor Product of 2 Vectors: $\mathbf{a}_{i}$ 
and 
$\mathbf{b}_{j}$

$\mathbf{c}_{i,j}=\mathbf{a}_{i}\otimes \mathbf{b}_{j}$
    
$\sum=E{[(x-\mu)(x-\mu)^{T}]}\approx\frac{1}{N-1}\sum_n^N(x_n-\overline{x})(x_n-\overline{x})^T$

Inner Product:

$\langle\mathbf{a}\mathbf{b}\rangle$

Is another name for a generalized dot product.  Unlike the dot product between two vectors, inner products in general can be defined even on infinite dimensional vector spaces.

In [49]:
a = np.array([1,2])
b = np.array([3,4])
c = np.outer(a,b)
c

array([[3, 4],
       [6, 8]])

In [47]:
np.inner(a,b)

11

In [48]:
a.dot(b)

11

In [50]:
np.diag(c)

array([3, 8])

In [52]:
np.diag(c).sum()

11

In [53]:
np.trace(c)

11

Eigenvalues and Eigenvectors
===

Linear equations $\mathbf{Ax}=\mathbf{b}$ come from steady state problems. Eigenvalues have their greatest importance in dynamic problems. The solution of $\frac{\text{d}\mathbf{u}}{\text{d}t}=A\mathbf{u}$ is changing with time—
growing or decaying or oscillating. We can’t find it by elimination. This chapter enters a
new part of linear algebra, based on $\mathbf{Ax}=\lambda\mathbf{x}$. All matrices in this chapter are square.
A good model comes from the powers $\mathbf{A}, \mathbf{A^2}, \mathbf{A^3}, ...$ of a matrix. Suppose you need the
hundredth power $\mathbf{A^{100}}$. The starting matrix A becomes unrecognizable after a few steps,
and $\mathbf{A^{100}}$ is very close to [.6 .6; .4 .4]:

$\mathbf{A}=\begin{bmatrix}8 & 3 \\2 & 7 \end{bmatrix} \mathbf{A^2}=\begin{bmatrix}70 & 45 \\30 & 55 \end{bmatrix}
\mathbf{A^3}=\begin{bmatrix}650 & 525 \\350 & 475 \end{bmatrix} ... \mathbf{A^{100}}=\begin{bmatrix}6000 & 6000 \\4000 & 4000 \end{bmatrix}$

$\mathbf{A^{100}}$ was found by using the eigenvalues of $\mathbf{A}$, not by multiplying 100 matrices. Those
eigenvalues (here they are 1 and 1/2) are a new way to see into the heart of a matrix.
To explain eigenvalues, we first explain eigenvectors. Almost all vectors change direction,
when they are multiplied by $\mathbf{A}$. Certain exceptional vectors x are in the same
direction as $\mathbf{Ax}$. Those are the “eigenvectors”. Multiply an eigenvector by $\mathbf{A}$, and the
vector $\mathbf{Ax}$ is a number $\lambda$ times the original $\mathbf{x}$.


<center>The basic equation is $\mathbf{Ax}=\lambda\mathbf{x}$. The number $\lambda$ is an eigenvalue of $\mathbf{A}$.</center>

SOURCE:http://math.mit.edu/~gs/linearalgebra/

In [55]:
X = np.random.randn(100,3)
cov = np.cov(X)
cov.shape

(100, 100)

When you calculate a covariance matrix, you must transpose it 1st.

In [57]:
cov = np.cov(X.T)
cov

array([[ 0.94884025,  0.00666893,  0.0058761 ],
       [ 0.00666893,  0.92505436, -0.0100413 ],
       [ 0.0058761 , -0.0100413 ,  0.77659835]])

In NumPy there are two types of eigenvector and eigenvalues:
(1) eigenvalues,eigenvector = np.eig()
OR
(2) eigenvalues,eigenvector = np.eigh()
eigh is for symmetric and Hermitian matrices

Symmetric means $\mathbf{A}=\mathbf{A^T}$

Hermitan means $\mathbf{A}=\mathbf{A^H}$

$\mathbf{A^H}$ is the conjugate transpose of 
$\mathbf{A}$

In [58]:
np.linalg.eigh(cov)

(array([ 0.77569189,  0.92416018,  0.95064089]),
 array([[ 0.03647832,  0.24332483,  0.96925866],
        [-0.06865301, -0.96700256,  0.24534223],
        [-0.99697347,  0.0754922 ,  0.01856964]]))

In [59]:
np.linalg.eig(cov)

(array([ 0.77569189,  0.95064089,  0.92416018]),
 array([[-0.03647832,  0.96925866,  0.24332483],
        [ 0.06865301,  0.24534223, -0.96700256],
        [ 0.99697347,  0.01856964,  0.0754922 ]]))

Solving a Linear System
===

Problem: $\mathbf{Ax=b}$

Solution: $\mathbf{A}^{-1}\mathbf{Ax=x=}\mathbf{A}^{-1}\mathbf{b}$

(1) Is a system of D equations and D unkowns

(2) $\mathbf{A}$ is DxD, assume it is invertable

(3) We have all the tools we need to solve this already:

    (a) Matrix inverse

    (b) Matrix multiply (dot)

In [60]:
A

array([[1, 2],
       [3, 4]])

In [62]:
b = np.array([1,2])
b

array([1, 2])

In [63]:
x = np.linalg.inv(A).dot(b)
x

array([  2.22044605e-16,   5.00000000e-01])

Never use the inv() method and only use solve(); it's more efficient and more accurate.

In [64]:
x = np.linalg.solve(A,b)
x

array([ 0. ,  0.5])