The Numpy Stack in Python
===========

Compare a List to a NumPy array:
--

In [12]:
import numpy as np

L = [1,2,3]
A = np.array([1,2,3])

for e in L:
    print e
    
for e in A:
    print e

1
2
3
1
2
3


In [13]:
L.append(4)
L

[1, 2, 3, 4]

or 

In [14]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [15]:
L2 = []
for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 10]

There is no method of append on a NumPy array:
We can use vector addition
----

In [16]:
A + A

array([2, 4, 6])

So the 1st lesson is + sign with Lists does concatenation while + sign with NumPy does vector addition.
---

In [17]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
2*A

array([2, 4, 6])

If you wanted to get the List elements to multiply, then you need to use the for loop.
---

In [19]:
L2 = []
for e in L:
    L2.append(e*e)
L2

[1, 4, 9, 16, 25]

In [20]:
A**2

array([1, 4, 9])

In [21]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [22]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [23]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

Dot Products
=====
$\mathbf{a}\cdot \mathbf{b}=\mathbf{a}^T\mathbf{b}=\sum _{d=1}^D a_d b_d$

$\mathbf{a} \cdot \mathbf{b}=\| \mathbf{a} \|\| \mathbf{b} \|\cos \theta _{\text{ab}}$

$\cos \theta _{\text{ab}}=\frac{\mathbf{a}^T\mathbf{b}}{\| \mathbf{a} \|\| \mathbf{b} \|}$

In [24]:
a = np.array([1,2])
b = np.array([2,1])

Slow dot product using for loops:
---

In [25]:
dot = 0
for e,f in zip(a,b):
    dot += e*f

dot

4

Fast using NumPy:
---

In [26]:
np.sum(a*b)

4

or as an alternative you could use the sum function as it's a instance method of numpy array itself

In [27]:
(a*b).sum()

4

With NumPy there's a more convenient way through the dot() function.
---

In [28]:
np.dot(a,b)

4

In [29]:
a.dot(b)

4

In [30]:
b.dot(a)

4

Angle between vectors requires us to calculate the length or magnitude of the vectors.
---
$\| \mathbf{a} \|=\sqrt{a_1^2+a_2^2+a_3^2+...+a_n^2+}$

In [32]:
amag=np.sqrt((a*a).sum())
amag

2.2360679774997898

As part of the Linear Algebra library within NumPy, we can use a convenient function: np.linalg.norm()

In [34]:
amag=np.linalg.norm(a)
amag

2.2360679774997898

Let's calculate the angle:

In [38]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.79999999999999982

In [39]:
angle=np.arccos(cosangle)
angle

0.6435011087932847